#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define DLG_MAIN                                100
#define ID_MAINMENU_SHOP                        101
#define ID_MAINMENU_SHOP_EXIT                   102
#define ID_MAINMENU_SHOP_FIRMY                  103
#define ID_MAINMENU_SHOP_ODDZIALY               104
#define ID_MAINMENU_SHOP_LOKALIZACJE            105
#define ID_MAINMENU_SHOP_PRODUKTY               106
#define ID_MAINMENU_SHOP_ZAKUPY                 107
#define DLG_FIRMY                               108
#define ID_MAINMENU_FIRMY                       109
#define ID_MAINMENU_FIRMY_EXIT                  110
#define ID_MAINMENU_FIRMY_DODAJ_FIRME           111
#define DLG_DODAJ_FIRMY                         112
#define ID_MAINMENU_ODDZIALY_EXIT               113
#define ID_MAINMENU_LOKALIZACJE_EXIT            114
#define ID_MAINMENU_PRODUKTY_EXIT               115
#define ID_MAINMENU_ZAKUPY_EXIT                 116
#define DLG_DODAJ_FIRMY_IDC_EDIT1               117
#define DLG_DODAJ_FIRMY_IDC_EDIT2               118
#define DLG_DODAJ_FIRMY_IDC_EDIT3               119
#define DLG_FIRMY_IDC_LIST1                     120
#define DLG_DODAJ_FIRMY_IDC_COMBO1              121
#define DLG_DODAJ_LOKALIZACJE                   124
#define DLG_LOKALIZACJE                         125
#define ID_MAINMENU_LOKALIZACJE_DODAJ_LOK       126
#define DLG_LOKALIZACJE_IDC_LIST1               127
#define DLG_ODDZIALY_IDC_LIST1                  128
#define DLG_ODDZIALY                            129
#define DLG_DODAJ_ODDZIAL                       131
#define DLG_DODAJ_PRODUKT                       133
#define DLG_DODAJ_ZAKUP                         135
#define DLG_PRODUKTY                            136
#define DLG_ZAKUPY                              137
#define IDI_ICON1                               138
#define DLG_DODAJ_ZAKUP1                        139
#define DLG_DODAJ_ODDZIAL_IDC_COMBO2            1000
#define DLG_DODAJ_ODDZIAL_IDC_EDIT1             1002
#define DLG_DODAJ_LOKALIZACJE_IDC_EDIT1         1004
#define DLG_DODAJ_LOKALIZACJE_IDC_EDIT2         1005
#define DLG_DODAJ_LOKALIZACJE_IDC_EDIT3         1006
#define DLG_DODAJ_LOKALIZACJE_IDC_COMBO1        1007
#define DLG_DODAJ_ODDZIAL_IDC_COMBO1            40000
#define DLG_DODAJ_PRODUKT_IDC_COMBO1            40000
#define DLG_DODAJ_ZAKUP1_COMBOBOX_ODDZIAL       40000
#define DLG_DODAJ_ZAKUP_COMBOBOX_FIRMA          40000
#define DLG_PRODUKT_IDC_LIST1                   40000
#define DLG_ZAKUPY_ID_LISTVIEW1                 40000
#define IDM_DODAJ_ODDZIA_1                      40000
#define IDM_DODAJ_PRODUKT1                      40000
#define IDM_DODAJ_ZAKUP1                        40000
#define DLG_DODAJ_PRODUKT_IDC_EDIT1             40001
#define DLG_DODAJ_ZAKUP1_DATA_ZAKUPU            40001
#define DLG_DODAJ_ZAKUP_COMBOBOX_ODDZIAL        40001
#define ID_MAINMENU_ZAKUPY_DODAJ_ZAKUPY         40001
#define DLG_DODAJ_PRODUKT_IDC_CHECKBOX1         40002
#define DLG_DODAJ_ZAKUP1_EDIT_ILOSC             40002
#define DLG_DODAJ_ZAKUP_COMBOBOX_PRODUKT        40002
#define DLG_DODAJ_ZAKUP1_DATA_WAZNOSCI          40003
#define DLG_DODAJ_ZAKUP_EDIT_CENA               40003
#define DLG_DODAJ_ZAKUP1_EDIT_CENA              40004
#define DLG_DODAJ_ZAKUP_EDIT_ILOSC              40004
#define DLG_DODAJ_ZAKUP1_BUTTON_DODAJ           40005
#define DLG_DODAJ_ZAKUP_DATA_WAZNOSCI           40005
#define DLG_DODAJ_ZAKUP1_COMBOBOX_PRODUKT       40006
#define DLG_DODAJ_ZAKUP_DATA_ZAKUPU             40006
#define DLG_DODAJ_ZAKUP1_COMBOBOX_FIRMA         40007
#define DLG_DODAJ_ZAKUP1_BUTTON_USUN            40008
#define DLG_DODAJ_ZAKUP1_LISTVIEW               40009
